### ISSUE TITLE
`id` is now a reserved field name in Terraform

### ISSUE THREAD

**Issue by samcrang** [russellcardullo/terraform-provider-pingdom#11]
[This commit](https://github.com/hashicorp/terraform/commit/67ceb1ab07acd55ebc0d7b6efb39019e73fd1888) in Terraform introduces `id` as a reserved field.

When building `terraform-provider-pingdom` against the Terraform code base including this commit then we end up with a plugin that generates the following error at runtime:

```* resource pingdom_check: id is a reserved field name for a resource
* module.foo.provider.pingdom: Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:

1 error(s) occurred:

* resource pingdom_check: id is a reserved field name for a resource
```

It's possible to workaround this by reseting back to a commit before this.

**Comment by jkapusi** [comment]
We just renamed the id field to rid (https://github.com/russellcardullo/terraform-provider-pingdom/blob/master/pingdom/resource_pingdom_check.go#L24) and its started to work again.

**Comment by russellcardullo** [comment]
It should be safe to just remove that entirely.  To test this, I removed `id` from the schema and when using the latest version of Terrraform (0.10.4) I was able to read and modify old state files prior to my change.

I just pushed that change up.  Let me know if that fixes the error.
