### ISSUE TITLE
Q: Does this work with 'new' pingdom and with terraform 0.11.X?

### ISSUE THREAD

**Issue by itsguy** [russellcardullo/terraform-provider-pingdom#15]
Any chance this still works?  Given new pingdom changes and terraform 0.11.X?

**Comment by elblivion** [comment]
Support for the latest Pingdom API was merged yesterday to go-pingdom: https://github.com/russellcardullo/go-pingdom/pull/20

@russellcardullo are you planning on also updating this provider?

**Comment by russellcardullo** [comment]
@elblivion Yes I'll be updating this within the next few days to support Pingdom 2.1 and Terraform 0.11.x.
