### ISSUE TITLE
"userids" does not support users who are Owners

### ISSUE THREAD

**Issue by lisaoakley** [russellcardullo/terraform-provider-pingdom#19]
"Who to alert?" section on the pingdom website allows you to select "Owner" type profiles as well as "Contact" type profiles, but adding the userid of an "Owner" type profile results in an error.

**Comment by russellcardullo** [comment]
Oh sorry for missing this old issue!  I just tried to reproduce but couldn't so I think it should be fixed by now but if anyone sees this again feel free to comment.
