### ISSUE TITLE
ping check is broken

### ISSUE THREAD

**Issue by rooty0** [russellcardullo/terraform-provider-pingdom#24]
When I'm trying to apply following 

```
resource "pingdom_check" "example_ping" {
  type                     = "ping"
  name                     = "aaaaaa"
  host                     = "8.8.8.8"
  resolution               = 1
}
```

I'm getting this
```
* pingdom_check.example_ping: 400 Bad Request: Invalid parameter value: sendnotificationwhendown
```
what does not make sense since [sendnotificationwhendown is not mandatory](https://www.pingdom.com/resources/api/2.1/#MethodCreate+New+Check), bad anyways when I fix that, so I have this
```
resource "pingdom_check" "example_ping" {
  type                     = "ping"
  name                     = "aaaaaa"
  host                     = "8.8.8.8"
  resolution               = 1
  sendnotificationwhendown = 1
}
``` 

API throws an 500 error

```
2019/01/17 13:02:48 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* pingdom_check.example_ping: 500 Internal Server Error: Internal Server Error
2019/01/17 13:02:48 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* pingdom_check.example_ping: 500 Internal Server Error: Internal Server Error

Error: Error applying plan:

1 error(s) occurred:

* pingdom_check.example_ping: 1 error(s) occurred:

* pingdom_check.example_ping: 500 Internal Server Error: Internal Server Error
```

THO I'm able to create a ping check with API using curl, so it's related to the provider for sure.

Will appreciate any help

**Comment by rooty0** [comment]
seems like latest version of go-pingdom library fixes this issue, @russellcardullo are you going to merge current PRs in the nearest future? There's a plenty of good stuff

**Comment by russellcardullo** [comment]
Thanks for filing this issue @rooty0.  I update some of the PRs and also had to add these two PRs: * https://github.com/russellcardullo/go-pingdom/pull/37.
* https://github.com/russellcardullo/terraform-provider-pingdom/pull/25

Once I added those I was able to create ping checks as in both of your examples.  Would you mind trying again and letting me know if things are working for you?
