### ISSUE TITLE
Cannot use imported resource without forced re-creation

### ISSUE THREAD

**Issue by kylegentle** [russellcardullo/terraform-provider-pingdom#31]
Because `resourcePingdomCheckRead` does not set the `"type"` attribute for checks, checks are imported with an empty `"type"` in the terraform state file. Since `"type"` is both `Required` and (correctly) specified with `ForceNew: true` in the resource schema, this forces a delete+create operation once the user properly specifies the `"type"` attribute in their resource file.

Steps to recreate:
1. Import a pingdom_check resource.
2. Update the resource block to properly reflect the imported check's existing configuration in Pingdom.
3. Run `terraform plan`.

**Comment by kylegentle** [comment]
Sorry about the open-close-open; I'm still getting used to the GitHub UI! :sweat_smile:

**Comment by russellcardullo** [comment]
Thanks for reporting this and for the PR!
