### ISSUE TITLE
Incompatible API version with plugin

### ISSUE THREAD

**Issue by tomasaberg** [russellcardullo/terraform-provider-pingdom#37]
Hi! 

This issue is similar to #6. Since [terraform 0.12](https://www.terraform.io/upgrade-guides/0-12.html) there's a new plugin version, which causes this error: `Error: Failed to instantiate provider "pingdom" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]`

Any thoughts how to fix it or is there any code involved to fix it?

Thank you!

**Comment by russellcardullo** [comment]
Hi @tomasaberg!  Yeah it looks like in order to use terraform 0.12.X with this plugin we need to update the dependencies.  I just opened #38 which should fix this for new terraform versions while staying compatible with terraform 0.11.X.
