### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by gtirloni** [russellcardullo/terraform-provider-pingdom#39]
Hi @russellcardullo! First let me thank you for all the work done here!

Would you consider doing release? It seems the last one was 4 years ago.

**Comment by phillbaker** [comment]
To piggy back on this issue - @russellcardullo would you accept a PR that added a travis config to build and push binaries to github releases (based on git tags)?

**Comment by russellcardullo** [comment]
Hi @gtirloni!  Just pushed tag v1.0.0 so you should be able to reference that tag as a proper release.

@phillbaker having cross compiled binaries pushed to github releases would be great.
