### ISSUE TITLE
Default URL value for HTTP checks

### ISSUE THREAD

**Issue by dcarley** [russellcardullo/terraform-provider-pingdom#4]
The `url` attribute is optional without a default, but the Pingdom API has a default of `/`. If you don't configure the attribute for an HTTP check then Terraform will report the following change on every run:

        pingdom_check.paas_http_healthcheck: Modifying...
          url: "/" => ""
        pingdom_check.paas_http_healthcheck: Modifications complete

        Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

Do you think it would be safe to set `Default: true` since `url` is only used if `check == "http"`?

**Comment by russellcardullo** [comment]
I think adding a default value makes sense.  I'll make the change now.

**Comment by dcarley** [comment]
Excellent, thanks!
