### ISSUE TITLE
Pingdom v3.1 api

### ISSUE THREAD

**Issue by joshsouza** [russellcardullo/terraform-provider-pingdom#42]
Pingdom released their v3.1 api in September of 2019, which has fewer features at the moment, but uses a different authentication method (tokens vs. username/password/key). 
To update this provider to use the 3.1 api also requires an update to the go client `go-pingdom`, so I've got a fork at https://github.com/grnhse/go-pingdom with the changes until the main repo is ready for 3.1.
My fork with the changes necessary for 3.1 support is here: https://github.com/grnhse/terraform-provider-pingdom/tree/api-v3.1

Not putting in a PR, as I think it makes sense to wait for the go-client to have a proper revision that supports v3 than to use my forked version, but hopefully this can help in the process up updating things to use the new API.

**Comment by russellcardullo** [comment]
Thanks for this.  Yes I agree we should get the go-client updated to support both 3.1 (as well as potentially continue to support 2.1 until it's fully deprecated in December 2020).

**Comment by abelal83** [comment]
support for versions 2.1 and below will end December 31, 2020. How can we use this provider to target the latest API? I noticed the latest API only accepts a token, the current way of authentication requires username, password and token.

**Comment by sergeunity** [comment]
Do we have news about the support of the news api version ?

**Comment by joshsouza** [comment]
I put in a PR for our fork, which would be entirely backwards incompatible. Up to @russellcardullo how he'd like to handle this. I can't devote much time, but I'm happy to help out if there's something else I can do.

**Comment by jlaffaye** [comment]
What's the status on the v3 API ?
The v2 API End Of Life is 31 december 2020.

**Comment by joshsouza** [comment]
@russellcardullo and I have been working on getting the dependent changes in `go-pingdom` ironed out, but I expect we'll be able to resolve that soon, at which point the linked PR will be ready for review, and should get everyone to an operational state on the 3.1 API. 
Note that this will be a breaking change, as it will change both the authentication parameters to the provider as well as the functionality of teams and users.
Fingers crossed we're a matter of weeks from that happening.

**Comment by joshsouza** [comment]
Resolved by https://github.com/russellcardullo/terraform-provider-pingdom/pull/77
