### ISSUE TITLE
Sensitive variables

### ISSUE THREAD

**Issue by ArnaldoLucienTema** [russellcardullo/terraform-provider-pingdom#43]
Is it possible to update private variables as sensitive [here](https://github.com/russellcardullo/terraform-provider-pingdom/blob/a053247a9085df79412c847e230c9ab7729de401/pingdom/provider.go#L19
)?

This will help in the Terraform Enterprise integration because when these values are `Sensitive` they will be hidden as `(sensitive)` in the logs - which is highly desired.

Please refer to how the official terraform module for the MongoDB Atlas Database User [resource](https://github.com/akshaykarle/terraform-provider-mongodbatlas/blob/master/mongodbatlas/resource_mongodbatlas_database_user.go#L37) has implemented.

**Comment by russellcardullo** [comment]
@ArnaldoLucienTema Sure thing and thanks for reporting this issue!  Just added a PR here in #44.  Let me know if that's what you're looking for.

**Comment by ArnaldoLucienTema** [comment]
Thanks a lot for the prompt response, I've added a little comment but this is exactly what I was looking for 👌

**Comment by ArnaldoLucienTema** [comment]
Hi, I've integrated your changes and the variables are still exposed in the terraform enterprise plan logs. Could you please test to see if flagging the variables as `Sensitive` is enough?

**Comment by russellcardullo** [comment]
Hi @ArnaldoLucienTema.  Would you mind sharing an example of what you're seeing (with sensitive values redacted)?

I double checked and didn't see any printing of the sensitive variables in either the plan or in the logs.  However I was checking with open source terraform.  Not sure if terraform enterprise works differently.
