### ISSUE TITLE
Invalid resource type

### ISSUE THREAD

**Issue by leylmordor** [russellcardullo/terraform-provider-pingdom#56]
Error: Invalid resource type

  on ../../main.tf line 14, in resource "pingdom_contact" "contacts":
  14: resource "pingdom_contact" "contacts" {

The provider provider.pingdom does not support resource type
"pingdom_contact".

Error: Invalid resource type

  on ../../main.tf line 14, in resource "pingdom_contact" "contacts":
  14: resource "pingdom_contact" "contacts" {

The provider provider.pingdom does not support resource type
"pingdom_contact".

**Comment by konstantin-kornienko** [comment]
same situation, please help!

**Comment by bakuyaku** [comment]
Rebuilding binary helped me to fix this problem. You should try it.

**Comment by sontags** [comment]
It appears the published binaries are broken, at least for linux/amd64. Rebuilding manually solves the issue. @russellcardullo Any chance to reupload fixed binaries? That would make the install process much easier... Thanks

**Comment by camerondavison** [comment]
The is the same for me on mac.

**Comment by marcuz** [comment]
@sontags they are not broken, release 1.1.1 doesn't include latest merges.

**Comment by russellcardullo** [comment]
I released a new 1.1.2 version today with all the latest merges.
