### ISSUE TITLE
New release tag post-Make?

### ISSUE THREAD

**Issue by robgmills** [russellcardullo/terraform-provider-pingdom#70]
Awesome Terraform provider!  Thanks for contributing it!  

Any chance we can get a new release/tag following the addition of Make to the build process in #48?  It looks like there were some good additions in #60 and #61 also!

Having this tag will help us pin to it in our CI/CD pipelines.

**Comment by marcuz** [comment]
@russellcardullo ping :)

**Comment by russellcardullo** [comment]
Hi!  I've published the latest release+tag here: https://github.com/russellcardullo/terraform-provider-pingdom/releases/tag/v1.1.2

This is also now available in the terraform registry as well: https://registry.terraform.io/providers/russellcardullo/pingdom/latest
