### ISSUE TITLE
Terraform 0.13 and community registry

### ISSUE THREAD

**Issue by nlamirault** [russellcardullo/terraform-provider-pingdom#74]
Hi, could you please provide a new version and publish it to the Terraform registry.
So we could use it like that : 

```hcl
terraform {
  required_providers {
    updown = {
      source = "russellcardullo/pingdom"
      version = "x.y.z"
    }
  }
}
```

There is some others providers : https://registry.terraform.io/search/providers?q=pingdom
But not yours. Thanks

**Comment by russellcardullo** [comment]
Hi!  I've published the latest release+tag here: https://github.com/russellcardullo/terraform-provider-pingdom/releases/tag/v1.1.2

This is also now available in the terraform registry as well: https://registry.terraform.io/providers/russellcardullo/pingdom/latest

**Comment by nlamirault** [comment]
@russellcardullo Cool ! Thanks.
