### ISSUE TITLE
Wish: Handle versioning according to SemVer

### ISSUE THREAD

**Issue by sontags** [russellcardullo/terraform-provider-pingdom#83]
Thanks @russellcardullo and @joshsouza for putting out v1.1.3. Also thanks for putting this project on My workflow got much easier https://registry.terraform.io/. That makes things much easier.

In order to get prepared for the Pingdom API v2.1 sunset I attempted a real quick update from v1.1.2 to v1.1.3. As the release versions suggested I did not expect much more work than increasing the provider version and running `terraform init -upgrade`. 

I ended up spending much more time, mainly due to the deprecation of the `pingdom_user` entity and the redesign of `pingdom_contact`. Don't get me wrong: Those changes are highly appreciated! But in order to allow other people plan a bit better it would be great to have a proper indication of the effort needed by bumping up the correct part of the version string according to SemVer.

Thats just a tiny wish for the future...

However, great work!

**Comment by russellcardullo** [comment]
I think we may be able to do this.  The one thing that would be an issue though is if anyone uses this repo as a module in another project (would be odd if that happened).  

The issue with v2 in modules is that according to golang specs we'd need to change all the import paths to have v2 in them: https://golangnews.org/2020/09/golang-modules-have-v2-problem/
