### ISSUE TITLE
pingdom_contact data source returns wrong ID

### ISSUE THREAD

**Issue by messiahUA** [russellcardullo/terraform-provider-pingdom#85]
I have data "pingdom_contact" "pagerduty" with the correct name and I see that it finds a proper contact in the terraform debug logs, but in the end, the actual id in the state is different (the last element of contacts list)

**Comment by marcelomilera** [comment]
I came across the same issue. It seems that there's a small bug when using the "pingdom_contact" data source that always ends up retrieving the last element of the contacts list.
This small PR should solve that #91
